$env:EXPRESS_SUPABASE_URL = "https://YOUR_PROJECT.supabase.co"
$env:EXPRESS_SUPABASE_SERVICE_KEY = "PASTE_YOUR_SECRET_SERVICE_ROLE_KEY_HERE"
$env:EXPRESS_BACKUP_DIR = "C:\Express Credit Ledger Backups"
