import{useEffect,useState}from'react';import{createClient}from'@supabase/supabase-js';import'./App.css';import'./upgrade.css';
const db=createClient('https://sddssihhredgeerpqfqw.supabase.co','sb_publishable_jpohOhZht8eDN2Pur3M9VQ_v0vfbeIf'),cash=n=>Number(n||0).toLocaleString()+' LBP';
function Login(){async function go(e){e.preventDefault();let f=new FormData(e.target),{error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)alert(error.message)}return <main className="login"><form onSubmit={go}><small>EXPRESS</small><h1>Credit Ledger</h1><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/><button>Sign in</button></form></main>}
function Popup({title,close,children}){return <div className="shade"><section className="modal"><button className="x" onClick={close}>×</button><h2>{title}</h2>{children}</section></div>}
export default function App(){const[session,setSession]=useState(),[me,setMe]=useState(),[cs,setCs]=useState([]),[tx,setTx]=useState([]),[users,setUsers]=useState([]),[settings,setSettings]=useState({exchange_rate_lbp_per_usd:90000,business_name:'Credit Ledger'}),[tab,setTab]=useState('entry'),[modal,setModal]=useState(),[pick,setPick]=useState(),[toast,setToast]=useState('');
useEffect(()=>{db.auth.getSession().then(x=>setSession(x.data.session));return db.auth.onAuthStateChange((_e,s)=>setSession(s)).data.subscription.unsubscribe},[]);async function load(){let[p,c,t,u,s]=await Promise.all([db.from('profiles').select('*').eq('id',session.user.id).single(),db.from('customer_balances').select('*').order('name'),db.from('ledger_transactions').select('*,customers(name),profiles(display_name)').order('created_at',{ascending:false}),db.from('profiles').select('*').order('created_at'),db.from('settings').select('*').single()]);setMe(p.data);setCs(c.data||[]);setTx(t.data||[]);setUsers(u.data||[]);if(s.data)setSettings(s.data)}useEffect(()=>{if(session)load()},[session]);function ok(x){setToast(x);setTimeout(()=>setToast(''),2200)}
if(!session)return <Login/>;if(!me)return <div className="loading">Loading…</div>;let owner=me.role==='owner',total=cs.reduce((a,c)=>a+Number(c.balance_lbp),0);
async function transact(e){e.preventDefault();let f=new FormData(e.target),{error}=await db.rpc('add_ledger_transaction',{p_customer_id:pick.id,p_type:modal,p_amount_lbp:Number(f.get('amount')),p_note:f.get('note')||null});if(error)return alert(error.message);setModal();await load();ok('Transaction saved')}
async function customer(e){e.preventDefault();let f=new FormData(e.target),data={name:f.get('name').trim(),phone:f.get('phone')||null,credit_limit_lbp:Number(f.get('limit')),notes:f.get('notes')||null,active:f.get('active')==='on'},q=pick?db.from('customers').update(data).eq('id',pick.id):db.from('customers').insert({...data,created_by:session.user.id}),{error}=await q;if(error)return alert(error.message);setModal();await load();ok(pick?'Customer updated':'Customer added')}
async function saveSettings(e){e.preventDefault();let f=new FormData(e.target),{error}=await db.from('settings').update({business_name:f.get('name'),exchange_rate_lbp_per_usd:Number(f.get('rate')),updated_by:session.user.id}).eq('id',true);if(error)return alert(error.message);await load();ok('Settings saved')}
async function reverse(id){if(!confirm('Reverse this transaction? Its effect will be cancelled but history will remain.'))return;let{error}=await db.rpc('reverse_transaction',{p_transaction_id:id,p_note:'Owner correction'});if(error)return alert(error.message);await load();ok('Transaction reversed')}
async function toggleUser(u){let{error}=await db.from('profiles').update({active:!u.active}).eq('id',u.id);if(error)return alert(error.message);await load();ok('User updated')}
async function changeEmail(e){e.preventDefault();let f=new FormData(e.target),email=f.get('email').trim().toLowerCase(),{error}=await db.auth.updateUser({email});if(error)return alert(error.message);e.target.reset();ok('Check the new email to confirm the change')}
return <div className="app">{toast&&<div className="toast">✓ {toast}</div>}<header><div><small>EXPRESS</small><h1>{settings.business_name}</h1></div><b>{me.display_name[0]}</b></header><main>
{tab==='entry'&&<><section className="total"><p>Total outstanding</p><h2>{cash(total)}</h2><span>${(total/settings.exchange_rate_lbp_per_usd).toFixed(2)} · Rate {Number(settings.exchange_rate_lbp_per_usd).toLocaleString()}</span></section><h2>Record a transaction</h2><div className="cards">{cs.filter(c=>c.active).map(c=><article key={c.id}><h3>{c.name}</h3><p>{cash(c.balance_lbp)} owed</p><small>Available: {cash(c.available_credit_lbp)}</small><div><button onClick={()=>{setPick(c);setModal('charge')}}>↑ Took goods</button><button onClick={()=>{setPick(c);setModal('payment')}} disabled={!Number(c.balance_lbp)}>↓ Paid</button></div></article>)}</div>{owner&&<button className="fab" onClick={()=>{setPick();setModal('customer')}}>＋ Add customer</button>}</>}
{tab==='customers'&&<><div className="pageTitle"><h2>Customers & limits</h2>{owner&&<button onClick={()=>{setPick();setModal('customer')}}>＋ Add</button>}</div><div className="list">{cs.map(c=><article key={c.id}><div><h3>{c.name} {!c.active&&<em>Blocked</em>}</h3><span>Limit {cash(c.credit_limit_lbp)} · Balance {cash(c.balance_lbp)}</span></div>{owner&&<button onClick={()=>{setPick(c);setModal('customer')}}>Edit</button>}</article>)}</div></>}
{tab==='history'&&<><h2>Transaction history</h2><div className="list history">{tx.map(t=><article key={t.id}><div><h3>{t.customers?.name} · {t.type}</h3><span>{cash(t.amount_lbp)} · {t.profiles?.display_name}<br/>{new Date(t.created_at).toLocaleString()}</span>{t.note&&<p>{t.note}</p>}</div>{owner&&t.type!=='reversal'&&!tx.some(x=>x.reverses_transaction_id===t.id)&&<button onClick={()=>reverse(t.id)}>Reverse</button>}</article>)}</div></>}
{tab==='settings'&&<><section className="panel"><h2>My login</h2><p>Current email: {session.user.email}</p><form onSubmit={changeEmail}><label>New email<input name="email" type="email" placeholder="Correct email address" required/></label><button>Change my email</button></form></section><section className="panel"><h2>Business settings</h2><form onSubmit={saveSettings}><label>System name<input name="name" defaultValue={settings.business_name}/></label><label>LBP per 1 USD<input name="rate" defaultValue={settings.exchange_rate_lbp_per_usd} inputMode="numeric"/></label>{owner&&<button>Save settings</button>}</form></section><section className="panel"><h2>System users</h2>{users.map(u=><article className="user" key={u.id}><div><h3>{u.display_name}</h3><p>{u.role} · {u.active?'Active':'Disabled'}</p></div>{owner&&u.id!==me.id&&<button onClick={()=>toggleUser(u)}>{u.active?'Disable':'Enable'}</button>}</article>)}</section><button className="signout" onClick={()=>db.auth.signOut()}>Sign out</button></>}
</main><nav>{[['entry','Entry'],['customers','Customers'],['history','History'],['settings','Settings']].map(([k,n])=><button className={tab===k?'on':''} onClick={()=>setTab(k)} key={k}>{n}</button>)}</nav>
{['charge','payment'].includes(modal)&&<Popup title={modal==='charge'?'Record goods taken':'Record payment'} close={()=>setModal()}><h3>{pick.name}</h3><form onSubmit={transact}><label>Amount in LBP<input name="amount" required inputMode="numeric" autoFocus/></label><label>Note (optional)<input name="note"/></label><button>Confirm</button></form></Popup>}
{modal==='customer'&&<Popup title={pick?'Edit customer':'Add customer'} close={()=>setModal()}><form onSubmit={customer}><label>Name<input name="name" required defaultValue={pick?.name}/></label><label>Phone<input name="phone" defaultValue={pick?.phone}/></label><label>Credit limit in LBP<input name="limit" required inputMode="numeric" defaultValue={pick?.credit_limit_lbp}/></label><label>Notes<input name="notes" defaultValue={pick?.notes}/></label><label className="check"><input type="checkbox" name="active" defaultChecked={pick?.active??true}/> Allowed to take on credit</label><button>Save customer</button></form></Popup>}</div>}
